Exception on /assist [POST]
Traceback (most recent call last):
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask_assistant/core.py", line 256, in _flask_assitant_view_func
    result = self._map_intent_to_view_func(view_func)()
  File "/home/sriram/projects/my_assist/my_assist/assistant/webhook.py", line 59, in getstatereminder
    rem=s["attributes"]["reminder"]
AttributeError: '_ListSelector' object has no attribute 'add_items'
Exception on /assist [POST]
Traceback (most recent call last):
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask_assistant/core.py", line 256, in _flask_assitant_view_func
    result = self._map_intent_to_view_func(view_func)()
  File "/home/sriram/projects/my_assist/my_assist/assistant/webhook.py", line 59, in getstatereminder
    rem=s["attributes"]["reminder"]
AttributeError: '_ListSelector' object has no attribute 'add_items'
Exception on /assist [POST]
Traceback (most recent call last):
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask_assistant/core.py", line 250, in _flask_assitant_view_func
    self.intent = self.request['result']['metadata']['intentName']
KeyError: 'intentName'
Exception on /assist [POST]
Traceback (most recent call last):
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask_assistant/core.py", line 256, in _flask_assitant_view_func
    result = self._map_intent_to_view_func(view_func)()
  File "/home/sriram/projects/my_assist/my_assist/assistant/webhook.py", line 59, in getstatereminder
    rem=s["attributes"]["reminder"]
AttributeError: '_ListSelector' object has no attribute 'add_items'
Exception on /assist [POST]
Traceback (most recent call last):
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sriram/projects/my_assist/env/local/lib/python2.7/site-packages/flask_assistant/core.py", line 256, in _flask_assitant_view_func
    result = self._map_intent_to_view_func(view_func)()
  File "/home/sriram/projects/my_assist/my_assist/assistant/webhook.py", line 59, in getstatereminder
    rem=s["attributes"]["reminder"]
AttributeError: '_ListSelector' object has no attribute 'add_items'
